spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
        - id: product_route
          uri: http://localhost:10500
          predicates:
            - Path=/product/{segment}