spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: product-service

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10500
  servlet:
    context-path: /product
logging:
  level:
    personal.skyxt.mallproduct: debug