spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 10400